src/Symfony/Installer/NewCommand.php

When the user tried to install the Symfony Standard Edition with just
specifying the minor version (like `symfony new blog 2.3`), the
installer failed for two reasons:
* The `use` statement for the `Client` class was missing when it was
used to download the list of available versions from symfony.com.
* The URL from where the archive should be downloaded was build before
the patch version was evaluated. Therefore, the archive of the actual
Symfony version to be installed could not be found (it was tried to
download an archive for `2.3` while the archive actually had to be
referenced for `2.3.26`).
This fixes #119.

fix handling of missing patch version

---

symfony

Windows uses Path instead of PATH which causes a notice for the about and download command.

set PATH environment variable for Windows

---

src/Symfony/Installer/DownloadCommand.php

At the moment, we don't have that many clues when people can't install Symfony and when we can't guess what is the problem with the backtrace.
This PR allows debugging easier, especially when Distill does throw an exception.
This is related to #129

Add previous exception for some 'unknown errors'

---

src/Symfony/Installer/NewCommand.php

In case of an exception, e.g. when typing an invalid version number, the `cleanUp` method gets called. Since the `README.md` file was dumped there, the target directory wasn't empty on the next try, so it wasn't possible to re-run the command without manually removing the file.

Don't create README.md on cleanup

---

src/Symfony/Installer/DemoCommand.php
src/Symfony/Installer/DownloadCommand.php
src/Symfony/Installer/NewCommand.php

Added support for a specific directory in demo command

---

src/Symfony/Installer/DownloadCommand.php

This fixes #163 by silencing the mistakenly thrown exception.

silence wrong exception

---

src/Symfony/Installer/DemoCommand.php

If `-> addArgument()` provides a default value for the `directory` argument, then the `!$input->getArgument('directory')` instruction will never be `true`. The result is that you cannot execute the `symfony demo` command repeatedly as you could in the previous versions:

Allow to execute the `symfony demo` command repeatedly

---

README.md

Updated README with instructions to generate a windows `symfony.bat` file, to allow for running the symfony installer globally.

Add tip to create windows executable

---

src/Symfony/Installer/NewCommand.php
tests/Symfony/Installer/Tests/IntegrationTest.php

This finishes #159, which is related to #144 and #143.
The new behavior of the installer:
1) When installing a regular Symfony version, nothing changes from the previous installer.
2) When you install a `beta` version, you see a warning message:
3) When you try to install a `dev` version, you get a better error message and a link to the article that will solve your problem:

Improve the installation of -dev and -BETA versions

---

src/Symfony/Installer/DownloadCommand.php

Symfony 3 is now the latest release. :tada: 
Fix the following issue:
```bash
symfony new test
Downloading Symfony...
4.93 MB/4.93 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%
Preparing project...
PHP Warning:  require(/Users/Ogi/test/app/SymfonyRequirements.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
Warning: require(/Users/Ogi/test/app/SymfonyRequirements.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php on line 265
PHP Fatal error:  require(): Failed opening required '/Users/Ogi/test/app/SymfonyRequirements.php' (include_path='.:/usr/local/php5/lib/php') in …
```

Fix Symfony3 is now the latest release

---

src/Symfony/Installer/DemoCommand.php

Those properties have been moved to the `DownloadCommand` in #205

Remove unnecessary properties

---

src/Symfony/Installer/DownloadCommand.php
src/Symfony/Installer/NewCommand.php

This is only a quick fix regarding the issue mentioned in #211 , and the few recent issues related:
- #217
- https://github.com/symfony/symfony/issues/16815

Keep .gitignore files in sync

---

src/Symfony/Installer/DownloadCommand.php

When guzzle is initalized it tries to find a suitable handler to use. If no handler can be found (for example curl) an exception is thrown.
With this change we try to find the handler before creating the client so that we can pass the handler to the client manually.
Doing this, we are able to customize the error message to make it (potentially) less confusing for the users who might have no idea what guzzle is.
The issue was found when looking at PR #200

Intercept and customize error from Guzzle

---

src/Symfony/Installer/NewCommand.php

remove pre-configured platform PHP version

---

tests/Symfony/Installer/Tests/IntegrationTest.php

Symfony released some stable versions with the `-DEV` suffix in their versions. This broke our tests. Let's fix this temporarily until the next maintenance versions are released next month.

Temporary fix for failing tests

---

src/Symfony/Installer/DownloadCommand.php
src/Symfony/Installer/SelfUpdateCommand.php

When the self-update command is initialized, the current version and latest version of the installer are not initialized.
The code is currently comparing NULL with NULL, which returns true.
By adding the parent::initialize() call, the DownloadCommand set the current and latest version of the installer, and then the version_compare function is actually really comparing the real versions.

#266 Self update is not detecting the installed version

---

README.md

This could help us mitigate the SSL issues on Windows while we solve them.
The contents were inspired by this section of the Humbug project by @padraic: https://github.com/padraic/humbug#self-update-request-debugging

Added a "troubleshooting" section in the README to solve common issues

---

src/Symfony/Installer/SelfUpdateCommand.php

In the past, I introduced several bugs that prevented to update the installer: first it was a server-side issue with version numbers ... and then it was a client-side issue while comparing versions (see #266). The only solution in those cases is to re-install the installer 😢 
To avoid further issues, I propose to add a `--force-update (-f)` option that updates the local installer to whichever version is published by Symfony, without checking or comparing any version.

Added an option to force the installer update

---

src/Symfony/Installer/DownloadCommand.php
src/Symfony/Installer/SelfUpdateCommand.php

Currently, the `self-update` command does not return an alerting enough exit message or status code on permission errors.
I saw in the code that it was intended, but it did not work well enough.
This PR fixes this issue by modifying the thrown exception type in certain cases, and by making the fallback exception to return error code 1, and by coloring the rollback message.
Before:
After:

Fixed some issues for the self-update command

---

src/Symfony/Installer/DownloadCommand.php

Less code to maintain for us and the output is almost the same:
---
Thanks to @mickaelandrieu who tweeted about this helper method and allowed me to learn about it!

Use Symfony's helper to format the memory values

---

src/Symfony/Installer/DemoCommand.php

This fixes #308 and it looks like this:

Display a warning message when installing the Demo application
